#默认使用配置
#spring:
#  profiles:
#    active: dev
#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.seven.iris.model
  mapperLocations: classpath:mappers/*.xml

#开发配置
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/activitilfp?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  activiti:
    check-process-definitions: false
    process-definition-location-prefix: classpath:/processes/
    database-schema-update: false